version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://backend:3000
